### ISSUE TITLE
2016 student instructions re IT setup?

### ISSUE THREAD

**Issue by benthestatistician** [bowers-illinois-edu/bowershansen-CI-course#7]
1.  What LMS's will the summer program be using: Ctools, Canvas, or both?
2.  Which LMS's are they recommending to instructor?
3.  Will they have use/need for UM Friend accounts?

Relevant to syllabus.

**Comment by benthestatistician** [comment]
It looks like the program's sticking with Ctools this summer.  So I've set up a course Ctools site, [here](https://ctools.umich.edu/portal/site/ef6d7adf-4545-4a10-bada-42b5b6bb9ed3).  Again they need to set up friend accounts, unless they decide to use their this-summer-only UM accounts (which is not advised). [master c7311fd] updatees the syllabus to say this.

**Comment by jwbowers** [comment]
Syllabus updated to reflect the site. IT instructions to be done once we know more (will we be using RStudio server?)

**Comment by benthestatistician** [comment]
No RStudio server (at least this summer).
